# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='books',
            new_name='uploaded_by',
        ),
    ]
