# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like_book', '0002_auto_20180120_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_books',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liked_users',
        ),
        migrations.AddField(
            model_name='book',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to='like_book.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
